---
name: "cenadi_job"
fs:
  url: "/Users/laure/Desktop/Doc1"
  update_rate: "5m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: true
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: true
  index_content: true
  attributes_support: true
  raw_metadata: true
  xml_support: false
  index_folders: false
  lang_detect: true
  continue_on_error: true
  pdf_ocr: true
  ocr:
    enabled: true
    pdf_strategy: "ocr_and_text"
  indexed_chars: -1
elasticsearch:
  urls:
  - "http://elasticsearch:9200"
  username: ""
  password: ""
  ssl_verification: false
  index: "cenadi_document1"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
